# ===============================================================
# (h2-in-memory) PROFILE
# ===============================================================
server:
  port: 8088
spring:
  # -----> Hibernate datasource
  datasource:
    url:
    platform: h2
    username:
    password:
    driver-class-name: org.h2.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: VehicleHealthServiceConnectionPool
      max-lifetime: 2000000
      connection-timeout: 60000
  # -----> JPA configurations
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  # -----> H2 settings
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  # -----> OAuth 2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            client-name:
          facebook:
            client-id:
            client-secret:
            client-name:
