server:
  port: 8088

custom:
  properties:
    endpoints:
       api:
         home: /api
         hello: /hello
       registration:
         home: /registration
         register-user-account: /register-user-account
         confirm-registration: /confirm
         confirmation-url: /confirm?token=
       logout:
         home: /logout
         success-url: ?logout
    cors-origins:
      front-end-module: http://localhost:8080
      back-end-module: http://localhost:8088

spring:
  profiles:
    active: dev-home
  # ===============================
  # = JavaMail Configuration
  # ===============================
  mail:
    default-encoding: utf-8
    host: smtp.gmail.com
    username: full.stack.web.app@gmail.com
    password: password_qwerty
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: false

---

spring:
  profiles: dev-home
# ===============================
# = Hibernate datasource
# ===============================
  datasource:
    url: jdbc:postgresql://localhost:5432/full-stack-web-app-db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect

---

spring:
  profiles: dev-office
# ===============================
# = Hibernate datasource
# ===============================
  datasource:
    url: jdbc:postgresql://localhost:5432/full-stack-web-app-db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect