# ===============================
# (SPRING)
# ===============================
spring:
  profiles:
    active: h2-in-memory
  # -----> JavaMail Configuration
  mail:
    default-encoding: UTF-8
    host:
    username:
    password:
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: false
  # -----> JPA configurations
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

# ===============================
# (JASYPT - Java Simplified Encryption)
# ===============================
jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.salt.RandomIVGenerator
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
    property:
      prefix: "ENC@["
      suffix: "]"

# ===============================
# (CUSTOM CONFIGURATION)
# ===============================
custom:
  properties:
    cors:
      front-end-app-local-host-url: http://localhost:8080/ui
      back-end-app-local-host-url: http://localhost:8088/api
    heroku:
      heroku-app-host-url: https://vehicle-health-service.herokuapp.com/ui
    jwt:
      token-secret-key:
      token-expiration:
    oauth2:
      short-lived-token-expiration:
    ui-message-codes:
      login-form-errors: "login-form-validation-errors"
      registration-form-errors: "registration-form-validation-errors"
      email-verification-token-empty: "email-verification-token-cannot-be-empty"
