# ===============================
# = (SPRING)
# ===============================
spring:
  profiles:
    active: h2-in-memory
  # -----> JavaMail Configuration
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: vehicle.health.service@gmail.com
    password: Pg91tmsecretHdvhs
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: false
  # -----> JPA configurations
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

# ===============================
# = (CUSTOM CONFIGURATION)
# ===============================
custom:
  properties:
    endpoints:
      api-context-path: /api
      registration:
        confirmation-url: /confirm?token=
        confirmed: /registration-confirmed
        confirmed-token-not-found: /registration-confirmed?error=tokenNotFound
        confirmed-token-expired: /registration-confirmed?error=tokenExpired
        system-could-not-enable-user-account: /registration-confirmed?error=systemEncounteredAnErrorOnEnablingAccount
        user-already-enabled: /registration-confirmed?info=userAlreadyEnabled
      authentication:
        failure-url: /login?error=true
      heroku:
        context-path: https://vehicle-health-service.herokuapp.com/ui
      oauth2:
        login-page: http://localhost:8080/login # TODO: must be updated because on production context is different (for now testing purpose)
        short-lived-millis: 2 # minutes (120000 nanoseconds)
        user-logged-in-using-google: /user-logged-in-using-google
        user-not-found: /user-not-found
        user-account-is-locked: /user-account-is-locked
        user-is-disabled: /user-is-disabled
        user-account-is-expired: /user-account-is-expired
        user-account-already-exists: /user-account-already-exists
        credentials-have-expired: /credentials-have-expired
        jwt-token-not-found: /jwt-token-not-found
        registration-provider-mismatch: /registration-provider-mismatch
        bad-credentials: /bad-credentials
        user-registered-using-google: /user-registered-using-google
        exchange-short-lived-token: /exchange-short-lived-token
        failure-target-url: /failure-target-url
    cors-origins:
      front-end-module: http://localhost:8080/ui
      back-end-module: http://localhost:8088/api
    jwt:
      secret: super-secret-authorization-token-password
      expiration: 15 # minutes (900000 nanoseconds)
    messages-language:
      header: Language