# ===============================
# = CUSTOM CONFIGURATION
# ===============================
custom:
  properties:
    endpoints:
      home:
       root: /
      server:
        root: /server
        health-check: /health-check
      registration:
        root: /registration
        register-user-account: /register-user-account
        confirm-registration: /confirm
        confirmation-url: /confirm?token=
        resend-email-verification-token: /resend-verification-token?token=
      logout:
        root: /logout
        success-url: ?logout
    cors-origins:
      front-end-module: http://localhost:8080
      back-end-module: http://localhost:8088

# ===============================
# = SPRING
# ===============================
spring:
  profiles:
    active: dev-home
  # ===============================
  # = JavaMail Configuration
  # ===============================
  mail:
    default-encoding: utf-8
    host: smtp.gmail.com
    username: full.stack.web.app@gmail.com
    password: password_qwerty
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: false

---

server:
  port: 8088
spring:
  profiles: dev-home
# ===============================
# = Hibernate datasource
# ===============================
  datasource:
    url: jdbc:postgresql://localhost:5432/full-stack-web-app-db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect

---

server:
  port: 8088
spring:
  profiles: dev-office
# ===============================
# = Hibernate datasource
# ===============================
  datasource:
    url: jdbc:postgresql://localhost:5432/full-stack-web-app-db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect

---

server:
  port: ${PORT:8080}
spring:
  profiles: heroku-deployment