# ===============================================================
# (dev-home) PROFILE
# ===============================================================
server:
  port: 8088
spring:
  # -----> Hibernate datasource
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: VehicleHealthServiceConnectionPool
      max-lifetime: 2000000
      connection-timeout: 60000
  # -----> JPA configurations
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  # -----> OAuth 2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            client-name:
          facebook:
            client-id:
            client-secret:
            client-name:
