# ===============================
# = (SPRING)
# ===============================
spring:
  profiles:
    active: h2-in-memory
  # -----> JavaMail Configuration
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: vehicle.health.service@gmail.com
    password: Pg91tmsecretHdvhs
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: false
  # -----> JPA configurations
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

# ===============================
# = (CUSTOM CONFIGURATION)
# ===============================
custom:
  properties:
    cors:
      front-end-app-local-host-url: http://localhost:8080/ui
      back-end-app-local-host-url: http://localhost:8088/api
    heroku:
      heroku-app-host-url: https://vehicle-health-service.herokuapp.com/ui
    jwt:
      token-secret-key: super-secret-authorization-token-password
      token-expiration: 15 # minutes (900000 nanoseconds)
    oauth2:
      short-lived-token-expiration: 2 # minutes (120000 nanoseconds)