# ===============================
# = CUSTOM CONFIGURATION
# ===============================
custom:
  properties:
    endpoints:
      server:
        root: /server
        health-check: /health-check
      registration:
        root: /registration
        register-user-account: /register-user-account
        confirm-registration: /confirm
        confirmation-url: /confirm?token=
        confirmed: /registration-confirmed
        confirmed-token-not-found: /registration-confirmed?error=tokenNotFound
        confirmed-token-expired: /registration-confirmed?error=tokenExpired
        user-already-enabled: /registration-confirmed?info=userAlreadyEnabled
        resend-email-verification-token: /resend-verification-token?token=
      authentication:
        root: /auth
        failure-url: /login?error=true
        principal-user: /principal-user
        refresh-token: /refresh-token
      logout:
        root: /logout
        success-url: ?logout
      heroku:
        app-url: https://vehicle-health-service.herokuapp.com
      vehicle-resource:
        root: /vehicles
        get-vehicle: /vehicles/vehicle/{ownerEmailAddress}
        get-current-mileage: /vehicles/vehicle/get-current-mileage/{ownerEmailAddress}
        update-current-mileage: /vehicles/vehicle/update-current-mileage/{ownerEmailAddress}
    cors-origins:
      front-end-module: http://localhost:8080
      back-end-module: http://localhost:8088
    jwt:
      header: Authorization
      secret: super-secret-authorization-token-password
      expiration: 900000
    messages-language:
      header: Language

# ===============================
# = SPRING
# ===============================
spring:
  profiles:
    active: dev-home
  # ===============================
  # = JavaMail Configuration
  # ===============================
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: vehicle.health.service@gmail.com
    password: Pg91tmsecretHdvhs
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: false
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

---

# ===============================================================
# = dev-home PROFILE
# ===============================================================
server:
  port: 8088
spring:
  profiles: dev-home
# ===============================
# = Hibernate datasource
# ===============================
  datasource:
    url: jdbc:postgresql://localhost:5432/full-stack-web-app-db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: VehicleHealthServiceConnectionPool
      max-lifetime: 2000000
      connection-timeout: 60000
# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect

---

# ===============================================================
# = dev-office PROFILE
# ===============================================================
server:
  port: 8088
spring:
  profiles: dev-office
# ===============================
# = Hibernate datasource
# ===============================
  datasource:
    url: jdbc:postgresql://localhost:5432/full-stack-web-app-db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: VehicleHealthServiceConnectionPool
      max-lifetime: 2000000
      connection-timeout: 60000
# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect

---

# ===============================================================
# = heroku-deployment PROFILE
# ===============================================================
server:
  port: ${PORT:8088}
spring:
  profiles: heroku-deployment
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: VehicleHealthServiceConnectionPool
      max-lifetime: 2000000
      connection-timeout: 60000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect