# ===============================
# = CUSTOM CONFIGURATION
# ===============================
custom:
  properties:
    endpoints:
      server:
        root: /server
        health-check: /health-check
      registration:
        root: /registration
        register-user-account: /register-user-account
        confirm-registration: /confirm
        confirmation-url: /confirm?token=
        confirmed: /registration-confirmed
        confirmed-token-not-found: /registration-confirmed?error=tokenNotFound
        confirmed-token-expired: /registration-confirmed?error=tokenExpired
        resend-email-verification-token: /resend-verification-token?token=
      authentication:
        root: /auth
        failure-url: /login?error=true
      logout:
        root: /logout
        success-url: ?logout
      heroku:
        app-url: https://heroku-web-app-backend-module.herokuapp.com
    cors-origins:
      front-end-module: http://localhost:8080
      back-end-module: http://localhost:8088
    jwt:
      header: Authorization
      secret: super-secret
      expiration: 900000

# ===============================
# = SPRING
# ===============================
spring:
  profiles:
    active: dev-home
  # ===============================
  # = JavaMail Configuration
  # ===============================
  mail:
    default-encoding: utf-8
    host: smtp.gmail.com
    username: full.stack.web.app@gmail.com
    password: password_qwerty
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: false
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

---

# ===============================================================
# = dev-home PROFILE
# ===============================================================
server:
  port: 8088
spring:
  profiles: dev-home
# ===============================
# = Hibernate datasource
# ===============================
  datasource:
    url: jdbc:postgresql://localhost:5432/full-stack-web-app-db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect

---

# ===============================================================
# = dev-office PROFILE
# ===============================================================
server:
  port: 8088
spring:
  profiles: dev-office
# ===============================
# = Hibernate datasource
# ===============================
  datasource:
    url: jdbc:postgresql://localhost:5432/full-stack-web-app-db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect

---

# ===============================================================
# = heroku-deployment PROFILE
# ===============================================================
server:
  port: ${PORT:8088}
spring:
  profiles: heroku-deployment
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect